services:
  # This matches your Postgres setup eventually, but let's add Redis now
  cache:
    image: redis:alpine
    container_name: myhives-redis
    ports:
      - '6379:6379' # Maps Windows 6379 to Container 6379
    restart: always

  db:
    image: postgres:14-alpine
    container_name: myhives-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./myhives_backup.sql:/docker-entrypoint-initdb.d/init.sql

  # Testna baza (Test DB)
  db_test:
    image: postgres:14-alpine
    container_name: myhives-postgres-test
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_test
    ports:
      - "${DB_PORT_TEST:-5433}:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      # Enaka init skripta ali posebna testna skripta za testno bazo
      - ./initial-hive-data.sql:/docker-entrypoint-initdb.d/init.sql

  # --- THIS PART WAS MISSING ---
volumes:
  postgres_data:
  postgres_test_data:

networks:
  default:
    name: myhives-network
